- name: parsed_users_job
  schema: parsed_data
  assets:
    - parsed_users
- name: parsed_accounts_job
  schema: parsed_data
  assets:
    - parsed_accounts
- name: h_accounts_job
  schema: data_vault
  assets:
    - h_accounts
- name: h_users_job
  schema: data_vault
  assets:
    - h_users
- name: l_users_accounts_job
  schema: data_vault
  assets:
    - l_users_accounts
- name: s_accounts_job
  schema: data_vault
  assets:
    - s_accounts
- name: s_users_job
  schema: data_vault
  assets:
    - s_users